USE db_video_club;

GO
CREATE TRIGGER tg_Dar_Baja_Cliente ON Cliente 
INSTEAD OF DELETE
AS
BEGIN
	BEGIN TRANSACTION
	BEGIN TRY
		DECLARE @COD_CLI VARCHAR(36) = (SELECT CodCli FROM deleted)
		UPDATE Cliente SET Estado = 0 WHERE CodCli = @COD_CLI
		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK
	END CATCH
END
GO