USE db_bares;

GO
ALTER PROCEDURE sp_Insertar_Persona
@DNI CHAR(8),
@NOMBRE VARCHAR(30)
AS
BEGIN
	BEGIN TRANSACTION
	BEGIN TRY

		-- LLAMA TG VALIDAR PERSONA ON Persona
		-- @SEE Tabla Persona
		INSERT INTO Persona(Dni, NombrePersona)
		VALUES
		(@DNI, UPPER(@NOMBRE))

		COMMIT TRANSACTION
		
	END TRY 
	BEGIN CATCH
		DECLARE @MENSAJE_ERR NVARCHAR(4000),
				@SEVERIDAD INT,
				@ESTADO INT
		SELECT
			@MENSAJE_ERR = ERROR_MESSAGE(),
			@SEVERIDAD = ERROR_SEVERITY(),
			@ESTADO = ERROR_STATE();
		RAISERROR(@MENSAJE_ERR ,@SEVERIDAD, @ESTADO)
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
	END CATCH
END
GO

