
GO
CREATE FUNCTION f_Letras_Aleatorias (@CANTCAR SMALLINT, @IS_UPPER TINYINT)
RETURNS VARCHAR(MAX)
AS
BEGIN
	DECLARE @LETRAS VARCHAR(26) = 'abcdefghijklmnopqrstuvwxyz'
	DECLARE @I INT = 0
	DECLARE @RSTRING VARCHAR(MAX) = ''
	
	IF @CANTCAR <= 0
		RETURN ''
	WHILE @I < @CANTCAR
	BEGIN
		DECLARE @RAN INT = FLOOR((SELECT * FROM vw_GET_RAND) * (LEN(@LETRAS))) + 1
		IF @IS_UPPER = 1
			SET @RSTRING = UPPER(@RSTRING + SUBSTRING(@LETRAS, @RAN, 1))
		ELSE
			SET @RSTRING = @RSTRING + SUBSTRING(@LETRAS, @RAN, 1)
		SET @I = @I + 1 
	END
	RETURN @RSTRING
END
GO