
GO
CREATE FUNCTION f_Numeros_Aleatorios (@CANTCAR BIGINT)
RETURNS VARCHAR(MAX)
AS
BEGIN
	DECLARE @NUMEROS CHAR(10) = '0123456789'
	DECLARE @I INT = 0
	DECLARE @RSTRING VARCHAR(MAX) = ''
	
	IF @CANTCAR <= 0
		RETURN ''
	WHILE @I < @CANTCAR
	BEGIN
		DECLARE @RAN INT = FLOOR((SELECT * FROM vw_GET_RAND) * (LEN(@NUMEROS))) + 1
		SET @RSTRING = UPPER(@RSTRING + SUBSTRING(@NUMEROS, @RAN, 1))
		SET @I = @I + 1 
	END
	RETURN @RSTRING
END
GO

