USE db_con_visual_studio

GO
CREATE OR ALTER FUNCTION f_Validar_Fecha (@FECHA VARCHAR(20))
RETURNS INT
AS
BEGIN
	RETURN
	(
		SELECT
			CASE 
				WHEN TRY_CONVERT(DATETIME, @FECHA) IS NOT NULL THEN 1
				ELSE 0
			END AS Result
	)
END
GO