USE db_video_club;

GO
CREATE PROCEDURE sp_Dar_Alta_Cliente
@COD_CLIENTE VARCHAR(36)
AS
BEGIN
	BEGIN TRANSACTION
	BEGIN TRY
	IF NOT EXISTS (SELECT * FROM Cliente WHERE CodCli = @COD_CLIENTE)
	BEGIN
		PRINT('Cliente Inexistente')
		ROLLBACK TRANSACTION
		RETURN
	END

	UPDATE Cliente SET Estado = 1 WHERE CodCli = @COD_CLIENTE

	COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
	END CATCH
END
GO