USE db_video_club;


GO
CREATE PROCEDURE sp_Insertar_Genero
@NOMBRE_GEN VARCHAR(20)
AS
BEGIN
	BEGIN TRANSACTION
	BEGIN TRY
		IF @NOMBRE_GEN IS NULL OR
			@NOMBRE_GEN LIKE '%[^a-zA-Z ]%'
		BEGIN
			PRINT ('Nombre del género es erroneo')
			ROLLBACK TRANSACTION
			RETURN
		END

		DECLARE @ID_GEN TINYINT = (SELECT COUNT(1) FROM Genero) + 1
		SET @NOMBRE_GEN = TRIM(UPPER(@NOMBRE_GEN))

		INSERT INTO Genero(IdGenero, NombreGenero)
		VALUES
		(@ID_GEN, @NOMBRE_GEN)

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION
	END CATCH
END
GO