
GO
CREATE OR ALTER FUNCTION f_Validar_Dni(@DNI VARCHAR(10))
RETURNS INT
AS
BEGIN
	
	SET @DNI = TRIM(@DNI)
	DECLARE @LEN INT = LEN(@DNI)
	DECLARE @IND INT = 0
	DECLARE @CAR VARCHAR(1) = ''

	IF @LEN > 8 OR @LEN < 7
		RETURN 0

	WHILE @IND < @LEN 
	BEGIN
		SET @CAR = SUBSTRING(@DNI, @IND, 1)
		IF CAST(@CAR AS INT) < 0 OR CAST(@CAR AS INT) > 9
			RETURN 0
		SET @IND = @IND + 1
	END

	RETURN 1
END
GO